name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./src

      - name: Test
        run: |
          go test -v ./src -coverprofile=coverage.out
          mkdir coverage-report
          touch coverage-report/index.html
          go tool cover -html=coverage.out -o=coverage-report/index.html

      - name: Generate coverage badge
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://img.shields.io/badge/Coverage-90%25-brightgreen'
          method: 'GET'
      
      - name: Dump generated page into github pages
        run: |
          touch coverage-report/coverage-badge.svg
          echo ${{ steps.myRequest.outputs.response }} > coverage-report/coverage-badge.svg

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage-report