name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./src

      - name: Test
        run: |
          go test -v ./src -coverprofile=coverage.out
          mkdir coverage-report
          touch coverage-report/index.html
          go tool cover -html=coverage.out -o=coverage-report/index.html

      - name: Generate coverage badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Test coverage'
          status: '53.4%'
          color: 'blue,555,daf'
          path: 'coverage-report/coverage-badge.svg'

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage-report