name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./src

      - name: Test
        run: |
          go test -v ./src -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -html=coverage-report/index.html

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage-report