name: Tests & Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: |
          go test -v ./... -coverprofile=coverage.out
          mkdir coverage-report
          touch coverage-report/index.html
          go tool cover -html=coverage.out -o=coverage-report/index.html
          go tool cover -func=coverage.out -o=coverage.out
          pct=$(cat coverage.out | grep total | grep -Po '\d+(?:\.\d+)?%')
          echo "COVERAGE_PERCENTAGE=$pct" >> $GITHUB_ENV
          pct=$(echo $pct | sed "s/%//")
          pct_int=${pct/\.*}
          if [[ $pct_int -lt 30 ]]; then
            color=red
          elif [[ $pct_int -lt 70 ]]; then
            color=orange
          else
            color=green
          fi
          echo "COVERAGE_BADGE_COLOR=$(echo $color)" >> $GITHUB_ENV

      - name: Generate coverage badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Coverage'
          status: ${{ env.COVERAGE_PERCENTAGE }}
          color: ${{ env.COVERAGE_BADGE_COLOR }}
          path: 'coverage-report/coverage-badge.svg'

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage-report